/* Transação */
DROP database if exists TRANSACAO;
CREATE DATABASE TRANSACAO;
USE TRANSACAO;
CREATE TABLE ALUNOS
(
	MATRICULA INT  NOT NULL,
	NOME VARCHAR(200) NULL,
	CPF VARCHAR(11)
);
SELECT * FROM ALUNOS;

START TRANSACTION;

INSERT ALUNOS 
        ( NOME, CPF )
VALUES  ( 'JOÃO','11111111111');

/*Abra outra guia e execute o comando abaixo*/
SELECT * FROM ALUNOS;

/* COMMIT */
ROLLBACK;
