/*Transações*/
USE master
GO
CREATE DATABASE TRANSACAO
GO
USE TRANSACAO
GO
CREATE TABLE [ALUNOS]
(
	[MATRICULA] [INT] IDENTITY(1,1) NOT NULL,
	[NOME] [VARCHAR](200) NULL,
	[CPF] [VARCHAR](11)
)
GO
SELECT * FROM ALUNOS

BEGIN TRAN DORNEL

INSERT dbo.ALUNOS 
        ( NOME, CPF )
VALUES  ( 'JOÃO','11111111111')

/*Abra outra guia e execute o comando abaixo*/
SELECT * FROM dbo.ALUNOS (NOLOCK)

--COMMIT
ROLLBACK